version: "3"

services:
  book_sales:
    build:
      context: ./book_sales
    container_name: book_sales_dev
    ports:
      - "8888:8888"
    hostname: postgres
    restart: always
    volumes:
      - ./book_sales:/app/book_sales

  book_upload:
    build:
      context: ./book_upload
    container_name: book_upload_dev
    ports:
      - "8080:8080"
    hostname: postgres
    restart: always
    volumes:
      - ./book_sales:/app/book_upload

  db_book:
    build:
      context: ./db_book
    container_name: db_book_dev
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - PGPASSWORD=admin
      - POSTGRES_DB=db_book_dev
      - DATABASE_HOST=localhost
    restart: always
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

volumes:
  db-data:
