version: "3"

services:
  book_sales:
    build:
      context: ./book_sales
    container_name: book_sales_dev
    ports:
      - "8888:8888"
    networks:
      - book2020
    restart: always
    volumes:
      - ./book_sales/src:/app/src

  book_upload:
    build:
      context: ./book_upload
    container_name: book_upload_dev
    ports:
      - "8080:8080"
    networks:
      - book2020
    restart: always
    volumes:
      - ./book_upload/src:/app/src

  graphql_book:
    build:
      context: ./graphql_book
    container_name: graphql_book_dev
    ports:
      - "7777:7777"
    networks:
      - book2020
    restart: always
    volumes:
      - ./graphql_book/schemas:/app/schemas
      - ./graphql_book/server.js:/app/server.js

  db_book:
    build:
      context: ./db_book
    container_name: db_book_dev
    ports:
      - "5432:5432"
    networks:
      - book2020
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - PGPASSWORD=admin
      - POSTGRES_DB=db_book_dev
      - DATABASE_HOST=localhost
    restart: always

volumes:
  db-data:

networks:
  book2020:
    driver: bridge
